# Generated by Django 4.1.2 on 2022-12-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
